name: IPTV-Go-test

on:
  workflow_dispatch:

permissions:
  contents: write  # 添加写入权限用于创建Release

jobs:
  linux_amd64_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cross Compile
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o allinone_linux_amd64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allinone_linux_amd64
          path: ./allinone_linux_amd64

  linux_arm64_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cross Compile
        run: |
          GOOS=linux GOARCH=arm64 go build -o allinone_linux_arm64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allinone_linux_arm64
          path: ./allinone_linux_arm64

  darwin_amd64_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cross Compile
        run: |
          GOOS=darwin GOARCH=amd64 go build -o allinone_darwin_amd64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allinone_darwin_amd64
          path: ./allinone_darwin_amd64

  darwin_arm64_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cross Compile
        run: |
          GOOS=darwin GOARCH=arm64 go build -o allinone_darwin_arm64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allinone_darwin_arm64
          path: ./allinone_darwin_arm64
  
  windows_amd64_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cross Compile
        run: |
          GOOS=windows GOARCH=amd64 go build -o allinone_windows_amd64.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allinone_windows_amd64.exe
          path: ./allinone_windows_amd64.exe

  create_release:
    needs: [  # 依赖所有构建任务
      linux_amd64_build,
      linux_arm64_build,
      darwin_amd64_build,
      darwin_arm64_build,
      windows_amd64_build
    ]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Release ${{ github.run_id }}"
          tag_name: "release-${{ github.run_id }}"
          files: |
            ./allinone_linux_amd64
            ./allinone_linux_arm64
            ./allinone_darwin_amd64
            ./allinone_darwin_arm64
            ./allinone_windows_amd64.exe
